go.property("gamepad_id", -1)
go.property("number", -1)
go.property("locked", true)
go.property("tint", vmath.vector4(1, 1, 1, 1))
go.property("shieldExport", false)

local damageTime = 0.1

local function sign(x)
	-- returns the sign of a value x > 0: 1, x = 0: 0, x < 0: -1
	if x > 0 then
		return 1
	elseif x < 0 then
		return -1
	else
		return 0
	end
end

local function destroyCharacter(self)
	msg.post("/ui#map", "setHealth", {player = self.number, health = self.health})
	msg.post("/controller#map-controller", "character_destroyed", {number = self.number})
	go.delete(".", true)
end

local function calculateDragCoefficients(self)
	local config = self.kinematics.drag


	config.lateralDragCoefficient = self.kinematics.acceleration/(math.exp(config.lateralDragConstant * config.lateral_terminal_velocity) - 1)
	config.longtitudinalDragCoefficieD = self.kinematics.acceleration/(math.exp(config.longtitudinalDragConstant * config.longtitudinal_terminal_velocity) - 1)
end

local function tableToVectorOverride(vector, list)
	if types.is_vector3(vector) then
		return #list > 0 and vmath.vector3(list[1] or vector.x,list[2] or vector.y,list[3] or vector.z) or vmath.vector3(list.x or vector.x,list.y or vector.y,list.z or vector.z)
	elseif types.is_vector4(vector) then
		return #list > 0 and vmath.vector4(list[1] or vector.x,list[2] or vector.y,list[3] or vector.z,list[4] or vector.w) or vmath.vector4(list.x or vector.x,list.y or vector.y,list.z or vector.z, list.w or vector.w)
	elseif types.is_quat(vector) then
		return #list > 0 and vmath.quat(list[1] or vector.x,list[2] or vector.y,list[3] or vector.z,list[4] or vector.w) or vmath.quat(list.x or vector.x,list.y or vector.y,list.z or vector.z, list.w or vector.w)
	end
	return vector -- Not actually a vector we can handle so leave it alone
end

local function mergeTables(base, override)
	-- Recursively overwrite base using override
	for key, value in pairs(override) do
		if type(value) == "table" and type(base[key]) == "userdata" then
			base[key] = tableToVectorOverride(base[key], value) -- Override vector components
		elseif type(value) == "table" and #value == 0 and type(base[key]) == "table" and #value == 0 then
			mergeTables(base[key], value)
		else
			base[key] = value
			print("Overriding "..key.." with: ")
			pprint(value)
			print("--")
		end
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	msg.post("#damageCircle", "disable")
	msg.post("#shield", "disable")

	local defaults = json.decode(sys.load_resource("/config/defaults.json"))
	
	self.velocity = vmath.vector3()
	self.position = go.get_position()
	self.rotation = go.get_rotation()
	self.direction = vmath.vector3(1,0,0)

	-- IF A PROPERTY IS NIL IT MUST BE EDITED VIA /config/defaults.json and not here
	
	self.health = nil
	
	self.kinematics = {
		accelerationDefault = nil,
		acceleration = nil, -- Exception
		drag = {
			lateralDragConstant = nil, -- Adjusts the smoothness of the exponetial drag growth (-1: decays up to TV, 0: UNDEFINED (straight line), 1: grows up to TV very very very quickly )
			longtitudinalDragConstant = nil,
			lateralTerminalVelocity = nil,
			longtitudinalTerminalVelocity = nil,
			dragCap = nil,
		},
		bounceCoefficient = nil

	}

	self.shield = {
		time = nil,
		cooldownTime = nil,
		cooldownTimeCurrent = 0,
		cooldown = false,
		animTime = nil,
		status = false,
		minsize = vmath.vector3(),
		fullsize = vmath.vector3(),
		currentFrame = 1
	}

	self.input = {
		horizontal = 0,
		vertical = 0,

		horizontal2 = 0,
		vertical2 = 0,

		rTrigger = false,
		lTrigger = false,

		b = false,

		lShoulder = false,
	}

	self.weapon = {
		rotation = vmath.quat(),
		id = "weapon",
		fireTime = nil,
		ammo = 0,
		ammoFactory = "magazine#ammo-factory",
		ammos = {}, -- An ordered list of ammo indicator objects
		magazine = nil,
		reloadBarMax = 281,
		reloadTime = nil,
		reloadTimeCurrent = 0,
		repeating = nil,
		fired = false,
		ready = true,
	}

	self.bullet = {
		init = {},
		onTick = {},
		onImpact = {},
		damage = nil,
		speed = nil,
		tint = vmath.vector4(),
		offset = nil
	}

	self.boost = {
		acceleration = nil,
		regenPause = nil,
		maxTime = nil,
		regenRate = nil,
		regen = false,
		time = 0,
		handle = nil,

		bar = {
			id = "boostBar#sprite",
			maxSize = 900 * go.get_scale().x,
		}
	}

	self.trail = {
		id = "trail#trail-factory",
		time = 0,
		maxTime = nil,
		trails = {},
		lifeTime = nil,
		scale = nil
	}

	mergeTables(self, defaults)
	
		
end

local function finaiseProperties(self)
	self.kinematics.accelerationDefault = self.kinematics.acceleration

	-- Add offset correction
	self.bullet.offset = self.bullet.offset * go.get_scale().x

	calculateDragCoefficients(self)

	msg.post("/ui#map", "setHealth", {player = self.number, health = self.health})
end

local function move(self, dir, force)
	if not self.locked then
		self.velocity = self.velocity + dir * force
	end
	local angle = math.atan2(-dir.x, dir.y)
	self.rotation = vmath.quat_rotation_z(angle)
end

local function resetWeapon(self, handle, time_elasped)
	self.weapon.ready = true;
end

local function removeAmmo(self)
	if self.weapon.ammo > 0 then
		self.weapon.ammo = self.weapon.ammo - 1
		self.weapon.reloadTimeCurrent = 0 -- Reset reload time
		go.delete(table.remove(self.weapon.ammos), false) -- Remove last ammo object from world and list
	end
end

local function addAmmo(self, count)
	for i = 1,count do
		local ammo = factory.create(self.weapon.ammoFactory)
		table.insert(self.weapon.ammos, ammo)
		go.set_parent(ammo, "magazine", false)
		go.set_rotation(vmath.quat(), ammo)
		go.set_position(vmath.vector3(-30 * (math.floor(self.weapon.ammo / 4)), 60 * math.fmod(self.weapon.ammo, 4), 0), ammo)
		self.weapon.ammo = self.weapon.ammo + 1
	end
end

local function updateReloadBar(self)
	local size = self.weapon.reloadTimeCurrent / self.weapon.reloadTime * self.weapon.reloadBarMax
	go.set("magazine#reload-bar", "size.y", size)
end

local function resetDamageCircle(self, handle, time_elapsed)
	msg.post("#damageCircle", "disable")
	
end

local function startRegen(self, handle, time_elasped)
	self.boost.regen = true
end

local function destroyTrail(self, handle, time_elapsed)
	go.delete(table.remove(self.trail.trails, 1))
end

local function resetShield(self, handle, time_elapsed)
	go.set("#shield", "scale", self.shield.minsize)
	self.shieldExport = false
	self.shield.status = false
	self.shield.cooldown = true
	self.shield.currentFrame = 1
	sprite.play_flipbook("#shield", "1")
end

function fixed_update(self, dt)
	if self.input.horizontal ~= 0 or self.input.vertical ~= 0 then
		self.direction = vmath.normalize(vmath.vector3(self.input.horizontal, self.input.vertical, 0))
		move(self, self.direction, self.kinematics.acceleration * dt)

		-- Spawn trail
		if self.trail.time < 0 and not self.locked then 
			local trail = factory.create(self.trail.id, self.position - vmath.vector3(0, 0, 0.01), self.rotation, {}, self.trail.scale * go.get_scale().x)
			go.set(msg.url(nil, trail, "sprite"), "tint", self.tint)
			table.insert(self.trail.trails, trail)
			timer.delay(self.trail.lifeTime, false, destroyTrail)
			self.trail.time = self.trail.maxTime
		elseif not self.locked then
			self.trail.time = self.trail.time - dt
		end
	end

	-- Set position and rotation
	self.position = go.get_position()
	self.position = self.position + self.velocity * dt
	go.set_position(self.position)
	go.set_rotation(self.rotation)

	-- Set the rotation of the rotationAnchor to cancel local rotation
	go.set_rotation(vmath.conj(self.rotation), "rotationAnchor")


	-- Shield
	if not self.shield.status and self.input.lTrigger and not self.shield.cooldown then
		self.shield.status = true
		self.shieldExport = true
		msg.post("#shield","enable")
		go.animate("#shield", "scale", go.PLAYBACK_ONCE_FORWARD, self.shield.fullsize, go.EASING_LINEAR, self.shield.animTime, 0, nil)
		timer.delay(self.shield.time, false, resetShield)
	elseif self.shield.cooldown then
		if self.shield.cooldownTimeCurrent < self.shield.cooldownTime then
			-- Update Display
			if self.shield.cooldownTime * self.shield.currentFrame / 9 < self.shield.cooldownTimeCurrent then
				self.shield.currentFrame = self.shield.currentFrame + 1
				sprite.play_flipbook("#shield", tostring(self.shield.currentFrame))
			end
			self.shield.cooldownTimeCurrent = self.shield.cooldownTimeCurrent + dt
		else
			self.shield.cooldown = false
			self.shield.cooldownTimeCurrent = 0
			msg.post("#shield", "disable")
		end
	end
	
	-- Weapon rotation
	-- The weapon should be rotated such that it faces in the direction of the secondary axis
	-- independent of the state of the main body, it must cancel out main body rotation
	if self.input.horizontal2 ~= 0 or self.input.vertical2 ~= 0 then
		local direction2 = vmath.normalize(vmath.vector3(self.input.horizontal2, self.input.vertical2, 0))
		local angle = math.atan2(-direction2.x, direction2.y)
		self.weapon.rotation = vmath.quat_rotation_z(angle)
		go.set_rotation(vmath.conj(self.rotation) * self.weapon.rotation, self.weapon.id)
	else
		self.weapon.rotation = go.get_world_rotation(self.weapon.id)
	end
	
	-- Hard boundry protection
	-- Send a collision event facing backtowards the map with distance equal to the distance outside the map
	if self.position.x > 2900 then -- If outside on the right
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(-1, 0, 0), distance = math.abs(self.position.x - 2900)})
	elseif self.position.x < 0 then -- If outside on the left
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(1, 0, 0), distance = math.abs(self.position.x)})
	elseif self.position.y > 1700 then -- If outside at the top
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(0, -1, 0), distance = math.abs(self.position.y - 1700)})
	elseif self.position.y < 0 then -- If outside at the bottom
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(0, 1, 0), distance = math.abs(self.position.y)})
	end

	-- Boost
	self.kinematics.acceleration = self.kinematics.accelerationDefault
	
	-- If boosting and some time is left
	if (self.input.b or self.input.lShoulder) and self.boost.time > 0 and not self.locked then
		timer.cancel(self.boost.handle)
		self.boost.regen = false
		self.kinematics.acceleration = self.kinematics.acceleration + self.boost.acceleration
		self.boost.time = self.boost.time - dt

	-- If currently regening and not full and not trying to boost
	elseif self.boost.time < self.boost.maxTime and self.boost.regen and not (self.input.b or self.input.lShoulder) then
		self.boost.time = self.boost.time + self.boost.regenRate * dt

	-- If not regening and not full and not trying to boost
	elseif self.boost.time < self.boost.maxTime and not (self.input.b or self.input.lShoulder) then
		self.boost.handle = timer.delay(self.boost.regenPause, false, startRegen)
	end
	-- Boost bar
	go.set(self.boost.bar.id, "size.x", 200 * self.boost.time/self.boost.maxTime)
	
	-- Drag is a vector representing the force to apply to oppose motion
	-- The drag coefficient for sideways (latteral) and forwards (longtitudinal)
	-- It is dependent on both velocity and facing direction
	-- To calculate:
	-- Caluclate the perpendicular and parallel components of the velocity
	-- Invert them and apply the 2 drag coefficients
	-- Map this vector back to the x-y plane using a rotation


	-- Normalised parallel
	-- local direction
	
	-- Normalised perpendicular
	local normal = vmath.vector3(-self.direction.y, self.direction.x, 0)

	local parallel_speed = vmath.dot(self.direction, -self.velocity)
	local perpendicular_speed = vmath.dot(normal, -self.velocity)
	
	local parallel_drag = sign(parallel_speed) * (self.kinematics.drag.longtitudinalDragCoefficient * math.exp(math.abs(parallel_speed) * self.kinematics.drag.longtitudinalDragConstant) - self.kinematics.drag.longtitudinalDragCoefficieD)
	local perpendicular_drag = sign(perpendicular_speed) * (self.kinematics.drag.lateralDragCoefficient * math.exp(math.abs(perpendicular_speed) * self.kinematics.drag.lateralDragConstant) - self.kinematics.drag.lateralDragCoefficient)

	-- Apply a cap to ensure the numbers don't go crazy
	parallel_drag = math.min(parallel_drag, self.kinematics.drag.dragCap)
	parallel_drag = math.max(parallel_drag, -self.kinematics.drag.dragCap)
	perpendicular_drag = math.min(perpendicular_drag, self.kinematics.drag.dragCap)
	perpendicular_drag = math.max(perpendicular_drag, -self.kinematics.drag.dragCap)
	
	local drag = self.direction * parallel_drag + normal * perpendicular_drag

	self.velocity = self.velocity + (dt * drag)

	-- Weapon firing reset
	if self.weapon.fired and not self.input.rTrigger then
		self.weapon.fired = false
	end
	-- Weapon
	if self.weapon.ready and self.weapon.ammo > 0 and self.input.rTrigger and ((not self.weapon.fired) or self.weapon.repeating) and not self.locked then
		msg.post("/controller", "fire_bullet", {position = self.position, rotation = self.weapon.rotation, properties = self.bullet})
		removeAmmo(self)
		self.weapon.ready = false
		self.weapon.fired = true
		timer.delay(self.weapon.fireTime, false, resetWeapon)
	end

	-- Ammo managment
	if self.weapon.reloadTimeCurrent > self.weapon.reloadTime and self.weapon.ammo < self.weapon.magazine then
		addAmmo(self, self.weapon.magazine - self.weapon.ammo)
		msg.post("magazine#reload-bar", "disable")
	elseif self.weapon.ammo < self.weapon.magazine then
		if self.weapon.ammo == 0 then
			msg.post("magazine#reload-bar", "enable")
			updateReloadBar(self)
		end
		self.weapon.reloadTimeCurrent = self.weapon.reloadTimeCurrent + dt
	end
	
	-- Gather debug
	msg.post("map:/controller","debug_data",{data = {
		direction = string.format("%.1f,%.1f", self.direction.x, self.direction.y),
		velocity = string.format("%.1f,%.1f", self.velocity.x, self.velocity.y),
		speed = string.format("%.1f",vmath.length(self.velocity))}})

end


function on_input(self, action_id, action)
	if action.gamepad ~= self.gamepad_id or self.gamepad_id == nil then
		return
	end
	if action_id == hash("Lstick_up") then
		if action.value > 0.1 then
			self.input.vertical = action.value
		else
			self.input.vertical = 0
		end
	elseif action_id == hash("Lstick_down") then
		if action.value > 0.1 then
			self.input.vertical = -action.value
		else
			self.input.vertical = 0
		end

	elseif action_id == hash("Lstick_left") then
		if action.value > 0.1 then
			self.input.horizontal = -action.value
		else
			self.input.horizontal = 0
		end

	elseif action_id == hash("Lstick_right") then
		if action.value > 0.1 then
			self.input.horizontal = action.value
		else
			self.input.horizontal = 0
		end

		-- Second stick / second axis

	elseif action_id == hash("Rstick_up") then
		if action.value > 0.1 then
			self.input.vertical2 = action.value
		else
			self.input.vertical2 = 0
		end
	elseif action_id == hash("Rstick_down") then
		if action.value > 0.1 then
			self.input.vertical2 = -action.value
		else
			self.input.vertical2 = 0
		end
	elseif action_id == hash("Rstick_left") then
		if action.value > 0.1 then
			self.input.horizontal2 = -action.value
		else
			self.input.horizontal2 = 0
		end

	elseif action_id == hash("Rstick_right") then
		if action.value > 0.1 then
			self.input.horizontal2 = action.value
		else
			self.input.horizontal2 = 0
		end
		-- Buttons

	elseif action_id == hash("B") then
		self.input.b = action.pressed or (not action.released)

		-- Shoulder

	elseif action_id == hash("Lshoulder") then
		self.input.lShoulder = action.pressed or (not action.released)

		
		-- Triggers

	elseif action_id == hash("Rtrigger") then
		self.input.rTrigger = action.value > 0.9

	elseif action_id == hash("Ltrigger") then
		self.input.lTrigger = action.value > 0.9
		

		-- D pad
	
	elseif action_id == hash("Dpad_up") then
		destroyCharacter(self)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") or message_id == hash("my_contact_point_response") then
		-- Handle Collision
		local newpos = go.get_position() + message.normal * message.distance
		local projection = vmath.dot(self.velocity, message.normal) -- Speed towards (or away) from the wall
		if projection < -40 then -- At high speed bounce
			self.velocity = (self.velocity - 2 * message.normal * projection) * self.kinematics.bounce_coefficient
		elseif projection < 0 then -- At low speed towards the wall
			-- Moving towards the wall, remove the component towards the wall
			self.velocity = self.velocity - projection * message.normal
		end -- Otherwise we're moving away do nothing
			
		go.set_position(newpos)
	elseif message_id == hash("damage") then
		msg.post("#damageCircle", "enable")
		timer.delay(damageTime, false, resetDamageCircle)

		self.health = self.health - message.damage
		msg.post("/ui#map", "setHealth", {player = self.number, health = self.health})

		if self.health <= 0 then -- Player is dead
			destroyCharacter(self)
		end
	elseif message_id == hash("property_override") then
		print("**** property override start PLAYER "..self.number.."*******************************************************")
		mergeTables(self, message.override)

		finaiseProperties(self)
	end
end

function final(self)
	for _, id in pairs(self.trail.trails) do
		go.delete(id, false)
	end
end