go.property("gamepad_id", -1)
go.property("locked", true)

local damageTime = 0.1

local function sign(x)
	-- returns the sign of a value x > 0: 1, x = 0: 0, x < 0: -1
	if x > 0 then
		return 1
	elseif x < 0 then
		return -1
	else
		return 0
	end
end

local function calculateDragCoefficients(self)
	local config = self.kinematics.drag

	config.lateral_drag_coefficient = self.kinematics.acceleration/(math.exp(config.lateral_drag_constant * config.lateral_terminal_velocity) - 1)
	config.longtitudinal_drag_coefficient = self.kinematics.acceleration/(math.exp(config.longtitudinal_drag_constant * config.longtitudinal_terminal_velocity) - 1)
end

function init(self)
	msg.post(".", "acquire_input_focus")

	go.set("#damageCircle", "tint", vmath.vector4(0,0,0,0))
	
	self.velocity = vmath.vector3()
	self.position = go.get_position()
	self.rotation = go.get_rotation()
	self.direction = vmath.vector3(1,0,0)
	
	self.kinematics = {


		acceleration = 1000,
		drag = {
			lateral_drag_constant = 0.0001, -- Adjusts the smoothness of the exponetial drag growth (-1: decays up to TV, 0: UNDEFINED, 1: grows up to TV very very very quickly )
			longtitudinal_drag_constant = 0.0001,
			lateral_terminal_velocity = 600,
			longtitudinal_terminal_velocity = 1000,
			drag_cap = 100000,
		},
		bounce_coefficient = 0.3

	}

	self.input = {
		horizontal = 0,
		vertical = 0,

		horizontal2 = 0,
		vertical2 = 0,

		rTrigger = false,
	}

	self.weapon = {
		rotation = vmath.quat(),
		id = "weapon",
		fireTime = 0.5,
		ready = true,
	}

	self.bullet = {
		init = {
			"setVelocity",
			"setOffset"
		},
		onTick = {
			"move"
		},
		onImpact = {
			"damageIfPlayer",
			"destroy"
		},
		speed = 1000,
		tint = vmath.vector4(1, 0.1, 0.1, 1),
		offset = 50
	}


	calculateDragCoefficients(self)
	
end

local function move(self, dir, force)
	if not self.locked then
		self.velocity = self.velocity + dir * force
	end
	local angle = math.atan2(-dir.x, dir.y)
	self.rotation = vmath.quat_rotation_z(angle)
end

local function resetWeapon(self, handle, time_elasped)
	self.weapon.ready = true;
end

local function resetDamageCircle(self, handle, time_elapsed)
	go.set("#damageCircle", "tint", vmath.vector4(0,0,0,0))
	
end

function fixed_update(self, dt)
	if self.input.horizontal ~= 0 or self.input.vertical ~= 0 then
		self.direction = vmath.normalize(vmath.vector3(self.input.horizontal, self.input.vertical, 0))
		move(self, self.direction, self.kinematics.acceleration * dt)
	end

	-- Set position and rotation
	self.position = go.get_position()
	self.position = self.position + self.velocity * dt
	go.set_position(self.position)
	go.set_rotation(self.rotation)


	-- Weapon rotation
	-- The weapon should be rotated such that it faces in the direction of the secondary axis
	-- independent of the state of the main body, it must cancel out main body rotation
	if self.input.horizontal2 ~= 0 or self.input.vertical2 ~= 0 then
		local direction2 = vmath.normalize(vmath.vector3(self.input.horizontal2, self.input.vertical2, 0))
		local angle = math.atan2(-direction2.x, direction2.y)
		self.weapon.rotation = vmath.quat_rotation_z(angle)
		go.set_rotation(vmath.conj(self.rotation) * self.weapon.rotation, self.weapon.id)
	else
		self.weapon.rotation = go.get_world_rotation(self.weapon.id)
	end
	
	-- Hard boundry protection
	-- Send a collision event facing backtowards the map with distance equal to the distance outside the map
	if self.position.x > 2900 then -- If outside on the right
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(-1, 0, 0), distance = math.abs(self.position.x - 2900)})
	elseif self.position.x < 0 then -- If outside on the left
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(1, 0, 0), distance = math.abs(self.position.x)})
	elseif self.position.y > 1700 then -- If outside at the top
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(0, -1, 0), distance = math.abs(self.position.y - 1700)})
	elseif self.position.y < 0 then -- If outside at the bottom
		msg.post(".", "my_contact_point_response", {normal = vmath.vector3(0, 1, 0), relative_velocity = vmath.vector3(), distance = math.abs(self.position.y)})
	end

	-- Drag is a vector representing the force to apply to oppose motion
	-- The drag coefficient for sideways (latteral) and forwards (longtitudinal)
	-- It is dependent on both velocity and facing direction
	-- To calculate:
	-- Caluclate the perpendicular and parallel components of the velocity
	-- Invert them and apply the 2 drag coefficients
	-- Map this vector back to the x-y plane using a rotation


	-- Normalised parallel
	-- local direction
	
	-- Normalised perpendicular
	local normal = vmath.vector3(-self.direction.y, self.direction.x, 0)

	local parallel_speed = vmath.dot(self.direction, -self.velocity)
	local perpendicular_speed = vmath.dot(normal, -self.velocity)
	
	local parallel_drag = sign(parallel_speed) * (self.kinematics.drag.longtitudinal_drag_coefficient * math.exp(math.abs(parallel_speed) * self.kinematics.drag.longtitudinal_drag_constant) - self.kinematics.drag.longtitudinal_drag_coefficient)
	local perpendicular_drag = sign(perpendicular_speed) * (self.kinematics.drag.lateral_drag_coefficient * math.exp(math.abs(perpendicular_speed) * self.kinematics.drag.lateral_drag_constant) - self.kinematics.drag.lateral_drag_coefficient)

	-- Apply a cap to ensure the numbers don't go crazy
	parallel_drag = math.min(parallel_drag, self.kinematics.drag.drag_cap)
	parallel_drag = math.max(parallel_drag, -self.kinematics.drag.drag_cap)
	perpendicular_drag = math.min(perpendicular_drag, self.kinematics.drag.drag_cap)
	perpendicular_drag = math.max(perpendicular_drag, -self.kinematics.drag.drag_cap)
	
	local drag = self.direction * parallel_drag + normal * perpendicular_drag

	self.velocity = self.velocity + (dt * drag)


	-- Weapon
	if self.weapon.ready and self.input.rTrigger and not self.locked then
		msg.post("/controller", "fire_bullet", {position = self.position, rotation = self.weapon.rotation, properties = self.bullet})
		self.weapon.ready = false
		timer.delay(self.weapon.fireTime, false, resetWeapon)
	end
	
	
	-- Gather debug
	msg.post("map:/controller","debug_data",{data = {
		direction = string.format("%.1f,%.1f", self.direction.x, self.direction.y),
		velocity = string.format("%.1f,%.1f", self.velocity.x, self.velocity.y),
		speed = string.format("%.1f",vmath.length(self.velocity))}})
end

function on_input(self, action_id, action)
	if action.gamepad ~= self.gamepad_id or self.gamepad_id == nil then
		return
	end
	if action_id == hash("Lstick_up") then
		self.input.vertical = action.value

	elseif action_id == hash("Lstick_down") then
		self.input.vertical = -action.value

	elseif action_id == hash("Lstick_left") then
		self.input.horizontal = -action.value

	elseif action_id == hash("Lstick_right") then
		self.input.horizontal = action.value

		-- Second stick / second axis

	elseif action_id == hash("Rstick_up") then
		self.input.vertical2 = action.value

	elseif action_id == hash("Rstick_down") then
		self.input.vertical2 = -action.value

	elseif action_id == hash("Rstick_left") then
		self.input.horizontal2 = -action.value

	elseif action_id == hash("Rstick_right") then
		self.input.horizontal2 = action.value

		-- Buttons

	elseif action_id == hash("gamepad_B") then
		self.input.b = action.pressed or (not action.released)

		-- Triggers

	elseif action_id == hash("Rtrigger") then
		self.input.rTrigger = action.value > 0.9


		-- D pad
	
	elseif action_id == hash("Dpad_up") then
		go.delete(".", true)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") or message_id == hash("my_contact_point_response") then
		-- Handle Collision
		local newpos = go.get_position() + message.normal * message.distance
		self.velocity = (self.velocity - 2 * message.normal * vmath.dot(self.velocity,message.normal)) * self.kinematics.bounce_coefficient
		go.set_position(newpos)
	elseif message_id == hash("damage") then
		go.set("#damageCircle", "tint", vmath.vector4(0.95,0.95,0.95,1))
		timer.delay(damageTime, false, resetDamageCircle)
	end
end