go.property("gamepad", 0)

function init(self)
	msg.post(".", "acquire_input_focus")

	self.velocity = vmath.vector3()
	self.position = go.get_position()	
	self.rotation = go.get_rotation()
	
	self.kinematics = {
		acceleration = 100,
		lateral_drag = 2,
		longtitudinal_drag = 1,
	}

	self.input = {
		horizontal = 0,
		vertical = 0
	}
	
end

local function move(self, dir, force)
	self.velocity = self.velocity + dir * force
	local angle = math.atan2(-dir.x, dir.y)
	self.rotation = vmath.quat_rotation_z(angle)
end

function update(self, dt)
	local direction = vmath.vector3(self.input.horizontal, self.input.vertical, 0)

	-- Movement force
	if direction.x ~= 0 and direction.y ~= 0 then
		direction = vmath.normalize(direction)
		move(self, direction, self.kinematics.acceleration)
	end

	-- Set position and rotation
	self.position = go.get_position()
	self.position = self.position + self.velocity * dt
	go.set_position(self.position)
	go.set_rotation(self.rotation)

	-- Drag
	local speed = vmath.length(self.velocity)
	local drag = self.kinematics.drag

	self.velocity = self.velocity * (1 - dt * drag)
end

function on_input(self, action_id, action)
	if action.gamepad ~= self.gamepad or self.gamepad == nil then
		return
	end
	print("input recived")
	print(action_id)
	pprint(action)
	if action_id == hash("Lstick_up") then
		self.input.vertical = action.value

	elseif action_id == hash("Lstick_down") then
		self.input.vertical = -action.value

	elseif action_id == hash("Lstick_left") then
		self.input.horizontal = -action.value

	elseif action_id == hash("Lstick_right") then
		self.input.horizontal = action.value

		-- Second stick / second axis

	elseif action_id == hash("gamepad_up_2") then
		self.input.vertical2 = action.value

	elseif action_id == hash("gamepad_down_2") then
		self.input.vertical2 = -action.value

	elseif action_id == hash("gamepad_left_2") then
		self.input.horizontal2 = -action.value

	elseif action_id == hash("gamepad_right_2") then
		self.input.horizontal2 = action.value

		-- Buttons

	elseif action_id == hash("gamepad_B") then
		self.input.b = action.pressed or (not action.released)

		-- Triggers

	elseif action_id == hash("gamepad_right_trigger") then
		self.input.rTrigger = action.value > 0.9
	end
end