function init(self)
	self.index = {0,0}
	self.grid = {{}}
	self.started = false
	self.hidden = false
	self.size = {0,0}
end

local function grid_get(self, index)
	-- This function is for conviniece and gets the properties from the grid using the index vector

	if index == nil then -- Stop if index is nil
		return
	end
	
	return self.grid[index[1]][index[2]]
end

local function move_to(self, new_index)
	-- This function converts an object index to a position and size and then moves the GO
	-- If the index is nil or 0,0 then maintain the current index and do nothing
	if new_index ~= nil then
		self.index = new_index
	else
		return
	end
	

	local new_pos = grid_get(self,self.index).position
	local new_size = grid_get(self,self.index).size

	go.set_position(new_pos)
	go.set("#sprite","size", new_size)
end

local function hide(self, hidden)
	self.hidden = hidden
	if hidden then
		msg.post("#sprite", "disable")
	else
		msg.post("#sprite", "enable")
	end
end

local function parse_grid(self, layout)
	for i = 1, layout.metadata.size[1] do
		self.grid[i] = {}
	end
	self.size = layout.metadata.size

	for name, data in pairs(layout.layout) do -- For each layout entry get it's name and value
		self.grid[data.index[1]][data.index[2]] = { -- Put in the grid under the index coordinates
			name = name, -- The name
			size = data.size, -- Size (vector3)
			position = data.position -- And Position (vector3)
		}
	end

	move_to(self,layout.metadata.starting_index) -- Set the starting position from the message

	if layout.metadata.hidden then -- Hide
		hide(self, true)
	end

end

local function update_grid(self, layout)
	parse_grid(self,layout)
end

local function start_grid(self, layout)	
	parse_grid(self,layout)

	move_to(self,layout.metadata.starting_index) -- Set the starting position from the message

	if layout.metadata.hidden then -- Hide
		hide(self, true)
	end
	
	self.started = true -- Set the started flag ready for the next message
end

local function find_next(self, direction)
	-- This function finds the next available space (not nil) in the direction provided
	-- It does this by moving in the direction and then if it does not find something it moves sideways till it does,
	-- There will never be an empty row
	local found = {self.index[1] + direction[1], self.index[2] + direction[2]}

	if found[1] < 0 or found[1] > self.size[1] or found[2] > self.size[2] or found[2] < 0 then
		return nil -- If the target extends outside the grid imediately return nil
	end	
	
	local count = 1
	while grid_get(self, found) == nil do -- If the target grid is empty
		if grid_get(self, {found[1] + count, found[2]}) ~= nil then -- Check left
			found = {found[1] + count, found[2]}
		elseif grid_get(self, {found[1], found[2] + count}) ~= nil then -- Check right
			found = {found[1], found[2] + count}
		end
		if count > 10 then
			return nil -- Safety break incase search finds nothing
		end
		count = count + 1 -- Expand the search in both directions
	end
	

	return found
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start") then -- The start message will just call the start function
		start_grid(self, message)
	elseif self.started == false then -- If not started end early
		return
	elseif message_id == hash("up") then
		move_to(self, find_next(self, {0,-1})) -- Set position to be one above current position
	elseif message_id == hash("down") then
		move_to(self, find_next(self, {0,1}))
	elseif message_id == hash("left") then
		move_to(self, find_next(self, {-1,0}))
	elseif message_id == hash("right") then
		move_to(self, find_next(self, {1,0}))
	elseif message_id == hash("hide") then
		hide(self, message.hidden)
	elseif message_id == hash("update") then
		update_grid(self, message)
	elseif message_id == hash("select") then
		msg.post(sender, "navigator_select", {selected = grid_get(self, self.index).name})
	end
end