components {
  id: "menu-navigator"
  component: "/main/menu-navigator/menu-navigator.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Menu Highlighter\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 100.0\n"
  "  y: 100.0\n"
  "  z: 100.0\n"
  "  w: 100.0\n"
  "}\n"
  "size {\n"
  "  x: 200.0\n"
  "  y: 200.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/menu-navigator/menu-navigator.atlas\"\n"
  "}\n"
  ""
}
