local maps = {
	"map1",
	"map2"
}

local winnerScreenTime = 3

local function showWinner(self, winner)
	go.set("/winnerScreen#winner-label", "color", vmath.vector4(self.players[winner].colour[1], self.players[winner].colour[2], self.players[winner].colour[3], 1))
	label.set_text("/winnerScreen#winner-label", "PLAYER ["..winner.."] WINS")
	msg.post("/winnerScreen", "enable")
end

local function hideWinner()
	msg.post("/winnerScreen", "disable")
end

local function load_map(map_name)
	msg.post("map:/controller", "load_map", {mapname = map_name})
end

local function unload_map()
	msg.post("#map-proxy", "disable")
	msg.post("#map-proxy", "final")
	msg.post("#map-proxy", "unload")
end

local function spawn_players(self)
	print("Spawing players")
	for i, player in ipairs(self.players) do
		print("Sending Message")
		msg.post(player.id, "spawn_character", {mapURL = "map:/controller"})
	end
end

local function start_players(self, message)
	for gamepad_id, player in pairs(message.players) do
		local id = factory.create("#player-factory", vmath.vector3(), vmath.quat(), {
			number = player.number,
			gamepad_id = gamepad_id,
			colour = vmath.vector4(player.colour[1], player.colour[2], player.colour[3], 1)
		})
		self.players[player.number] = {
			gamepad_id = gamepad_id,
			colour = player.colour,
			id = id,
			score = 0,
		}
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	msg.post("/winnerScreen","disable")
	go.set("/winnerScreen#sprite","tint",vmath.vector4(1, 1, 1, 0.6))
	
	self.players = {} -- A list of players indexed by number always without gaps

	self.mode = "MAP" -- The current state of the game indicating what to do next MAP/MOD
end

function on_message(self, message_id, message, sender)
	if message_id == hash("init_parameters") then
		-- Players is in the form
		-- {
		-- 	<gamepad> = {
		-- 	  number = int
		--    colour = {r,g,b}
		--    label = <invalid>
		-- 	}
		-- }
		start_players(self, message)
		msg.post("/ui#gameplay", "start", self.players)
		msg.post("#map-proxy","load")
	elseif message_id == hash("proxy_loaded") then
		msg.post(sender, "init")
		msg.post(sender, "enable")
		
		if self.mode == "MAP" then
			load_map(maps[math.random(#maps)])
			msg.post("map:/controller", "player_count", {count = #self.players})
			spawn_players(self)
		elseif self.mode == "MOD" then
			hideWinner()
			msg.post("modifiers:/controller", "init_parameters", {destroy_order = self.order, players = self.players})
		end
	elseif message_id == hash("proxy_unloaded") then
		if self.mode == "MAP" then 
			msg.post("#map-proxy", "load") -- start map again
		elseif self.mode == "MOD" then
			msg.post("#modifiers-proxy", "load") -- start modifiers
		end
	elseif message_id == hash("round_over") then
		self.mode = "MOD"
		
		local winner = message.order[#message.order]

		self.order = message.order

		self.players[winner].score = self.players[winner].score + 1
		msg.post("/ui#gameplay", "set_score", {number = winner, score = self.players[winner].score})
		
		
		showWinner(self, winner)
		
		timer.delay(winnerScreenTime, false, unload_map)
	elseif message_id == hash("picking_end") then
		self.mode = "MAP"

		for i, modifier in ipairs(message.modifiers) do
			local player_modifier = {
				title = modifier.title,
				properties = modifier.properties
			}
			
			msg.post(self.players[modifier.player].id, "add_modifier", {modifiers = {player_modifier}})
		end
		
		msg.post("#modifiers-proxy", "unload")
	end
end