-- A short lived map controlling script, designed to be destroyed after each round

local TimerLabel = "/countdown#countdown-label"
local Countdown = "/countdown"
local BlankTint = vmath.vector4(1, 1, 1, 0.6)

local Debug = "/debug"
local DebugTint = vmath.vector4(1, 1, 1, 0.5) 

local characterScale = 0.4

local bulletFactory = "#bullet-factory"

local mapReady = false
local mapContent = {}
local healthReady = false
local playersReady = false
local loadingDone = false

local function debug_menu_prep(self)
	go.set(Debug.."/menu#background", "tint", DebugTint)
	msg.post(Debug.."/menu", "disable")
end

local function debug_menu_show(self)
	msg.post(Debug.."/menu", "enable")
	self.debug.enabled = true
end

local function debug_menu_hide(self, name)
	msg.post(Debug.."/menu", "disable")
	self.debug.enabled = false
end

local function debug_menu_update(self)
	if self.debug.enabled then
		for menu_name, menu_data in pairs(self.debug.data) do
			local data = menu_name.."\n"
			for name, value in pairs(menu_data) do
				data = data..name..": "..value.."\n"
			end
			label.set_text(Debug.."/menu#"..menu_name, data)
		end
	end
end
	
local function next_second(self, handle, elapsed_time)
	if self.currentSecond <= 1 then
		msg.post(Countdown, "disable") -- If time is 0 disable the countdown
		for _, player in pairs(self.players) do
			go.set(msg.url(nil, player[hash("/character")], "character"), "locked", false) -- And unlock all players
		end
		timer.cancel(handle)
	else
		self.currentSecond = self.currentSecond - 1
		label.set_text(TimerLabel, tostring(self.currentSecond))
	end
end

local function start_countdown(self)
	label.set_text(TimerLabel, tostring(self.currentSecond))
	timer.delay(1, true, next_second)
end

local function prep_countdown(self)
	self.currentSecond = 3
	msg.post(Countdown, "enable")
	go.set(Countdown.."#sprite", "tint", BlankTint)
end

local function load_map(name)
	collectionfactory.load("#"..name.."-factory", function(self, url, result)
		if result then
			mapContent = collectionfactory.create(url)
			mapReady = true
		end
	end)
end

-- Bullet callbacks -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

local initCallbacks = {
	setVelocity = function(id, bullet)
		bullet.velocity = vmath.rotate(bullet.rotation, vmath.vector3(0, bullet.speed, 0))
	end,
	setOffset = function(id, bullet)
		bullet.position = bullet.position + vmath.rotate(bullet.rotation, vmath.vector3(0, bullet.offset, 0))
	end
}

local updateCallbacks = {
	move = function(id, bullet, dt)
		bullet.position = bullet.position + bullet.velocity * dt
	end,
}

local impactCallbacks = {
	moveToEdge = function(id, bullet, bullets, event, other_event, type)
		bullet.position = bullet.position + event.normal * event.distance
	end,
	damageIfPlayer = function(id, bullet, bullets, event, other_event, type)
		if type == hash("player_damage") and not go.get(msg.url(nil, other_event.id, "character"), "shieldExport") then
			msg.post(other_event.id, "damage", {damage = bullet.damage})
		elseif type == hash("player_damage") then
			bullet.velocity = -bullet.velocity
			bullet.doNotDestroy = true
		end
	end,
	destroy = function(id, bullet, bullets, event, other_event, type)
		if not bullet.doNotDestroy then
			bullets[id] = nil
			go.delete(id, false)
		end
		bullet.doNotDestroy = false
	end
}


-- Bullet callbacks end-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


local function create_bullet(position, rotation, tint)
	local bulletId = factory.create(bulletFactory, position, rotation, {}, 1)
	go.set(msg.url("map", bulletId, "sprite"), "tint", tint)
	return bulletId
end

local function init_bullet(id, bullet)
	for i, callback in ipairs(bullet.init) do
		initCallbacks[callback](id, bullet)
	end
	go.set_position(bullet.position, id)
end

local function impact_bullet(id, bullet, bullets, own_event, other_event, type)
	for i, callback in ipairs(bullet.onImpact) do
		impactCallbacks[callback](id, bullet, bullets, own_event, other_event, type)
	end
	go.set_position(bullet.position, id)
end

local function update_bullet(id, bullet, bullets, dt)
	for i, callback in ipairs(bullet.onTick) do
		updateCallbacks[callback](id, bullet, dt)
	end
	go.set_position(bullet.position, id)

	-- Hard boundary protection
	if bullet.position.x > 2900 then -- If outside on the right
		impact_bullet(id, bullet, bullets, {normal = vmath.vector3(-1, 0, 0), distance = 2900 - bullet.position.x}, {}, "border")
	elseif bullet.position.x < 0 then -- If outside on the left
		impact_bullet(id, bullet, bullets, {normal = vmath.vector3(1, 0, 0), distance = -bullet.position.x}, {}, "border")
	elseif bullet.position.y > 1700 then -- If outside at the top
		impact_bullet(id, bullet, bullets, {normal = vmath.vector3(0, -1, 0), distance = 1700 - bullet.position.y}, {}, "border")
	elseif bullet.position.y < 0 then -- If outside at the bottom
		impact_bullet(id, bullet, bullets, {normal = vmath.vector3(0, 1, 0), distance = -bullet.position.y}, {}, "border")
	end
end

local function physics_listener(self, events)
	for _, event in ipairs(events) do
		if event.type == hash("trigger_event") then
			-- Forward the message to the colliding objects (which are not bullets)
			local function send_side(self_side, other_side)
				msg.post(msg.url(nil, self_side.id, nil), "trigger_response", {
					enter = event.enter,
					other_id = other_side.id,
					other_group = other_side.group,
					own_group = self_side.group
				})
			end
			send_side(event.a, event.b)
			send_side(event.b, event.a)
		elseif event.type == hash("contact_point_event") then
			if self.bullets[event.a.id] then
				local type = event.b.group

				event.a.distance = event.distance
				
				impact_bullet(event.a.id, self.bullets[event.a.id], self.bullets, event.a, event.b, type)
			elseif self.bullets[event.b.id] then
				local type = event.a.group

				event.b.distance = event.distance
				
				impact_bullet(event.b.id, self.bullets[event.b.id], self.bullets, event.b, event.a, type)
			else
				-- Forward the message to the colliding objects (which are not bullets)
				local function send_side(self_side, other_side)
					msg.post(msg.url(nil, self_side.id, nil), "contact_point_response", {
						position = self_side.position,
						normal = self_side.normal,
						relative_velocity = self_side.relative_velocity,
						distance = event.distance,
						applied_impulse = event.applied_impulse,
						mass = self_side.mass,
						other_mass = other_side.mass,
						other_id = other_side.id,
						other_position = other_side.position,
						group = self_side.group,
						other_group = other_side.group,
						life_time = 1,
						own_group = self_side.group
					})
				end
				send_side(event.a, event.b)
				send_side(event.b, event.a)
			end
		end
	end
end

local function spawn_character(self, message)
	self.players[message.number] = collectionfactory.create("#character-factory",go.get_position(mapContent[hash("/spawn "..message.number)]), go.get_rotation(mapContent[hash("/spawn "..message.number)]), {}, characterScale)
	for object, properties in pairs(message.properties) do
		for fragment, values in pairs(properties) do
			for property, value in pairs(values) do
				go.set(msg.url("map", self.players[message.number][object], fragment), property, value)
			end
		end
	end	
end

local function healthBarPrep(self)
	local data = {}
	for i = 1,4 do
		if self.players[i] ~= nil then
			data["player"..i] = {
				colour = self.players[i].colour
			}
		end
	end
	msg.post("/ui#map", "start", data)
	healthReady = true
end

function init(self)
	msg.post(".", "acquire_input_focus")

	physics.set_event_listener(physics_listener)
	
	self.players = {} -- A table of players

	self.debug = {  -- Debug data
		enabled = false,
		data = {physics = {
			
		}}
	}

	self.playerCount = nil -- Set later
	
	self.destroyOrder = {} -- An ordered list of when each character died
	
	self.bullets = {} -- A list of bullets

	debug_menu_prep()
	prep_countdown(self)
end

function fixed_update(self, dt)
	for id, bullet in pairs(self.bullets) do
		update_bullet(id, bullet, self.bullets, dt)
	end

	if mapReady and playersReady and healthReady and not loadingDone then
		for i,v in pairs(self.players) do
			spawn_character(self, v)
		end
		loadingDone = true
		start_countdown(self)
	end
end

function on_input(self, action_id, action)
	if not action.pressed then
		return
	end
	if action_id == hash("open_debug") then
		if self.debug.enabled then
			debug_menu_hide(self)
		else
			debug_menu_show(self)
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("load_map") then
		load_map(message.mapname)
	elseif message_id == hash("spawn_character") then
		-- Add character to player list and update ready flag
		self.players[message.number] = message
		if #self.players == self.playerCount then
			playersReady = true
			-- Prepare health once players are all loaded
			healthBarPrep(self)
		end
	elseif message_id == hash("force_property") then
		go.set(self.players[message.number], message.property, message.value)
	elseif message_id == hash("debug_data") then
		self.debug.data.physics = message.data
		debug_menu_update(self)
	elseif message_id == hash("fire_bullet") then
		local bulletId = create_bullet(message.position, message.rotation, message.properties.tint)
		local bullet = message.properties
		bullet.position = message.position
		bullet.rotation = message.rotation
		
		self.bullets[bulletId] = message.properties

		init_bullet(bulletId, bullet)
	elseif message_id == hash("player_count") then
		self.playerCount = message.count
	elseif message_id == hash("character_destroyed") then
		table.insert(self.destroyOrder, message.number)
		self.players[message.number] = nil -- Remove from player list
		if #self.destroyOrder >= self.playerCount - 1 then
			local winner,_ = next(self.players)
			table.insert(self.destroyOrder, winner) -- Add winner to the end so we know they were last
			
			print("All players dead WINNER: PLAYER "..winner)
			msg.post("gameplay:/controller#gameplay-controller", "round_over", {order = self.destroyOrder})
		end
	end
end