-- A short lived map controlling script, designed to be destroyed after each round

local TimerLabel = "/countdown#countdown-label"
local Countdown = "/countdown"
local BlankTint = vmath.vector4(1, 1, 1, 0.4)

local Debug = "/debug"
local DebugTint = vmath.vector4(1, 1, 1, 0.5) 

local characterScale = 0.3

local bulletFactory = "#bullet-factory"

local function debug_menu_prep(self)
	go.set(Debug.."/menu#background", "tint", DebugTint)
	msg.post(Debug.."/menu", "disable")
end

local function debug_menu_show(self)
	msg.post(Debug.."/menu", "enable")
	self.debug.enabled = true
end

local function debug_menu_hide(self, name)
	msg.post(Debug.."/menu", "disable")
	self.debug.enabled = false
end

local function debug_menu_update(self)
	if self.debug.enabled then
		for menu_name, menu_data in pairs(self.debug.data) do
			local data = menu_name.."\n"
			for name, value in pairs(menu_data) do
				data = data..name..": "..value.."\n"
			end
			label.set_text(Debug.."/menu#"..menu_name, data)
		end
	end
end
	
local function next_second(self, handle, elapsed_time)
	if self.currentSecond <= 1 then
		msg.post(Countdown, "disable") -- If time is 0 disable the countdown
		for _, player in pairs(self.players) do
			go.set(msg.url(nil, player[hash("/character")], "character"), "locked", false) -- And unlock all players
		end
		timer.cancel(handle)
	else
		self.currentSecond = self.currentSecond - 1
		label.set_text(TimerLabel, tostring(self.currentSecond))
	end
end

local function start_countdown(self)
	self.currentSecond = 3
	msg.post(Countdown, "enable")
	go.set(Countdown.."#sprite", "tint", BlankTint)
	label.set_text(TimerLabel, tostring(self.currentSecond))
	timer.delay(1, true, next_second)
end

local function load_map(name)
	collectionfactory.set_prototype("#map-factory", "/main/gameplay/maps/"..name..".collectionc")
	return collectionfactory.create("#map-factory")
end

-- Bullet callbacks -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

local initCallbacks = {
	setVelocity = function(id, bullet)
		bullet.velocity = vmath.rotate(bullet.rotation, vmath.vector3(0, bullet.speed, 0))
	end,
	setOffset = function(id, bullet)
		bullet.position = bullet.position + vmath.rotate(bullet.rotation, vmath.vector3(0, bullet.offset, 0))
	end
}

local updateCallbacks = {
	move = function(id, bullet, dt)
		bullet.position = bullet.position + bullet.velocity * dt
	end,
}

local impactCallbacks = {
	damageIfPlayer = function(id, bullet, bullets, event, other_event, type)
		print(type)
		if type == hash("player") then
			msg.post(other_event.id, "damage", {damage = bullet.damage})
		end
	end,
	destroy = function(id, bullet, bullets, event, other_event, type)
		bullets[id] = nil
		go.delete(id, false)
	end
}


-- Bullet callbacks end-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


local function create_bullet(position, rotation, tint)
	local bulletId = factory.create(bulletFactory, position, rotation, {}, 1)
	go.set(msg.url("map", bulletId, "sprite"), "tint", tint)
	return bulletId
end

local function init_bullet(id, bullet)
	for i, callback in ipairs(bullet.init) do
		initCallbacks[callback](id, bullet)
	end
	go.set_position(bullet.position, id)
end

local function impact_bullet(id, bullet, bullets, own_event, other_event, type)
	for i, callback in ipairs(bullet.onImpact) do
		impactCallbacks[callback](id, bullet, bullets, own_event, other_event, type)
	end
	go.set_position(bullet.position, id)
end

local function update_bullet(id, bullet, bullets, dt)
	for i, callback in ipairs(bullet.onTick) do
		updateCallbacks[callback](id, bullet, dt)
	end
	go.set_position(bullet.position, id)

	-- Hard boundary protection
	if bullet.position.x > 2900 then -- If outside on the right
		impact_bullet(id, bullet, bullets, {}, {}, "border")
	elseif bullet.position.x < 0 then -- If outside on the left
		impact_bullet(id, bullet, bullets, {}, {}, "border")
	elseif bullet.position.y > 1700 then -- If outside at the top
		impact_bullet(id, bullet, bullets, {}, {}, "border")
	elseif bullet.position.y < 0 then -- If outside at the bottom
		impact_bullet(id, bullet, bullets, {}, {}, "border")
	end
end

local function physics_listener(self, events)
	for _, event in ipairs(events) do
		if event.type == hash("trigger_event") then
			if self.bullets[event.a.id] then
				local type = event.b.group
				
				impact_bullet(event.a.id, self.bullets[event.a.id], self.bullets, event.a, event.b, type)
			elseif self.bullets[event.b.id] then
				local type = event.a.group
				
				impact_bullet(event.b.id, self.bullets[event.b.id], self.bullets, event.b, event.a, type)
			end
		elseif event.type == hash("contact_point_event") then
			-- Forward the message to the colliding objects
			local function send_side(self_side, other_side)
				msg.post(msg.url(nil, self_side.id, nil), "contact_point_response", {
					position = self_side.position,
					normal = self_side.normal,
					relative_velocity = self_side.relative_velocity,
					distance = event.distance,
					applied_impulse = event.applied_impulse,
					mass = self_side.mass,
					other_mass = other_side.mass,
					other_id = other_side.id,
					other_position = other_side.position,
					group = self_side.group,
					other_group = other_side.group,
					life_time = 1,
					own_group = self_side.group
				})
			end
			send_side(event.a, event.b)
			send_side(event.b, event.a)
		end
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	physics.set_event_listener(physics_listener)
	
	self.players = {} -- A table of players

	self.debug = {  -- Debug data
		enabled = false,
		data = {physics = {
			
		}}
	}

	self.bullets = {} -- A list of bullets
	
	debug_menu_prep()
	
	start_countdown(self)
end

function fixed_update(self, dt)
	for id, bullet in pairs(self.bullets) do
		update_bullet(id, bullet, self.bullets, dt)
	end
end

function on_input(self, action_id, action)
	if not action.pressed then
		return
	end
	if action_id == hash("open_debug") then
		if self.debug.enabled then
			debug_menu_hide(self)
		else
			debug_menu_show(self)
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("load_map") then
		self.map = load_map(message.mapname)
	elseif message_id == hash("spawn_character") then
		self.players[message.number] = collectionfactory.create("#character-factory",go.get_position(self.map[hash("/spawn "..message.number)]), go.get_rotation(self.map[hash("/spawn "..message.number)]), {}, characterScale)
		for object, properties in pairs(message.properties) do
			for fragment, values in pairs(properties) do
				for property, value in pairs(values) do
					go.set(msg.url("map", self.players[message.number][object], fragment), property, value)
				end
			end
		end	
	elseif message_id == hash("force_property") then
		go.set(self.players[message.number], message.property, message.value)
	elseif message_id == hash("debug_data") then
		self.debug.data.physics = message.data
		debug_menu_update(self)
	elseif message_id == hash("fire_bullet") then
		local bulletId = create_bullet(message.position, message.rotation, message.properties.tint)
		local bullet = message.properties
		bullet.position = message.position
		bullet.rotation = message.rotation
		
		self.bullets[bulletId] = message.properties

		init_bullet(bulletId, bullet)
	end
end